### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [shpinderworka/pav_fin#3]
- [ ] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [ ] Использование фикстур
- [ ] Повторное использование шагов (собственная библиотека шагов)
- [ ] Фичи из воздуха
- [ ] Детализация фичи

**Comment by shpinderworka** [comment]
Fix было сделано раньше времени.
