### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [shpinderworka/pav_fin#4]
- [ ] Создать свой шаг проверяющий текст предупреждения

**Comment by alehinsasha** [comment]
Нужна помощь по этой задаче?

**Comment by shpinderworka** [comment]
Спасибо, пока сама. Много времени потратила, чтобы разобраться почему в следующей фиче подставляется вызов из прошлой и с тем, как работает этот механизм.
