### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [shpinderworka/pav_fin#6]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by shpinderworka** [comment]
Альбине Плохих pav@corp.aib.ru

**Comment by shpinderworka** [comment]
Спасибо огромное.

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by shpinderworka** [comment]
Подтверждаю, письмо получено, спасибо.
